In [1]:
import torch as t
import numpy as np

In [2]:
#创建一个numpy的ndarray
numpy_tensor = np.random.randn(10, 20)

# tensor与ndarray的相互转换
可以用以下两种方式将numpy的ndarray转换为pytorch的tensor

In [3]:
pytorch_tensor1 = t.Tensor(numpy_tensor)
pytorch_tensor2 = t.from_numpy(numpy_tensor)
print(pytorch_tensor1, "\n", pytorch_tensor2)

tensor([[-0.4073,  0.0540, -0.2382, -1.3170,  1.3284,  0.5807,  0.8022, -1.0928,
          1.3500, -1.0772, -0.3009,  0.9286, -0.3692, -0.2560, -1.3966, -0.6238,
         -1.9842,  2.5670, -0.7263, -0.6330],
        [ 1.6549, -2.0768,  0.9102, -0.6007,  0.1109,  1.4269, -0.1061,  1.0758,
         -0.8092, -0.1247,  0.1619,  0.5499,  1.1338, -0.5454,  0.4168,  2.0563,
         -0.1235,  0.5316,  0.9677, -1.8588],
        [-0.0396, -1.1029, -2.9897, -1.2262,  1.1872, -1.2366, -1.3382, -0.1344,
          1.5564,  0.5822, -0.4220, -0.8209,  1.1765,  0.6056, -0.7796, -1.3003,
         -0.8746,  0.0722,  0.7650, -1.1495],
        [-0.2582,  0.3231,  0.8763, -1.0808, -0.0996, -1.2569,  0.1388, -0.4465,
          0.0971,  1.2675,  0.7545, -1.5415,  0.7036, -0.4816, -1.0728, -1.5231,
         -1.7812, -0.5203, -0.2652, -1.6807],
        [ 0.7252,  0.3524, -0.0689,  0.7353,  0.0655,  0.7942, -0.5699,  0.6032,
          0.5172, -0.8373, -0.6800,  0.8066, -0.5375, -0.5477, -0.2844,  0.9363,
      

我们也可以用以下两种方式将pytorch tensor转换为numpy ndarray.
注意如果tensor在GPU上，不能直接转换为ndarray，要先通过.cpu()转换到CPU上后在转换成ndarray，否则会报错。

In [4]:
#tensor在cpu上
numpy_array1 = pytorch_tensor1.numpy()

#tensor在GPU上
numpy_array2 = pytorch_tensor2.cpu().numpy()

# PyTorch GPU加速
我们可以使用以下两种方式将tensor放到GPU上。

In [5]:
#第一种方式是定义CUDA数据类型
dtype = t.cuda.FloatTensor  #定义默认GPU数据类型
gup_tensor = t.Tensor(10, 20).type(dtype)

#第二种方式更简单，推荐使用
gpu_tensor1 = t.randn(10, 20).cuda(0) #将tensor放到第一个GPU上
gpu_tensor2 = t.randn(10, 20).cuda(1) #将tensor放到第二个GPU上

D:\Anaconda\lib\site-packages\torch\cuda\__init__.py:116: UserWarning: 
    Found GPU0 GeForce GT 750M which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


RuntimeError: CUDA error (10): invalid device ordinal

使用第一种方法将tensor放到GPU上时会将数据类型转换成指定的类型，而用第二种方法直接将tensor放到GPU上，类型和之前保持一致。推荐在定义tensor时就指定数据类型，再用第二种方式放到GPU上。

而将tensor放回CPU的操作非常简单

In [11]:
cpu_tensor = gpu_tensor.cpu()

NameError: name 'gpu_tensor' is not defined

# 访问tensor的一些属性

In [13]:
#通过以下两种方式获得tensor的大小
print(pytorch_tensor1.shape)
print(pytorch_tensor1.size())

torch.Size([10, 20])
torch.Size([10, 20])


In [15]:
#得到tensor的数据类型
print(pytorch_tensor1.type())

torch.FloatTensor


In [16]:
#得到tensor的维度
print(pytorch_tensor1.dim())

2


In [18]:
#得到tensor所有元素的个数
print(pytorch_tensor1.numel())

200


In [19]:
tensor_test = t.randn(3, 2)
tensor_test = tensor_test.type(t.DoubleTensor)
numpy_test = tensor_test.numpy()
print(numpy_test.dtype)

float64


# tensor的操作

tensor的操作和numpy非常相似，如果你熟悉numpy的操作，那么tensor基本上是一致的。下面来列举一些操作

In [38]:
x = t.ones(2, 2) #表示产生一个2x2的元素均为1的tensor
print(x)
print(x.type())

tensor([[1., 1.],
        [1., 1.]])
torch.FloatTensor


In [39]:
#将其转化为整型
x = x.long()
# x = x.type(t.LongTensor)
print(x.type())

torch.LongTensor


In [40]:
x = t.randn(3, 4)
print(x)

tensor([[-0.7186,  0.3988, -0.4838,  0.4351],
        [-0.5701,  0.4154,  1.4665,  0.1102],
        [ 0.1719,  0.4493, -0.6168, -0.5705]])


In [41]:
max_value, max_index = t.max(x, dim = 1) #沿着行取最大值，返回最大值以及最大值的索引
print(max_value, max_index)

tensor([0.4351, 1.4665, 0.4493]) tensor([3, 2, 1])


In [42]:
max_value, max_index = t.max(x, dim = 0) #沿着列取最大值，返回最大值以及最大值的索引
print(max_value, max_index)

tensor([0.1719, 0.4493, 1.4665, 0.4351]) tensor([2, 2, 1, 0])


In [43]:
#沿着行对x求和
sum_x_raw = t.sum(x, dim = 1)
print(sum_x_raw)

tensor([-0.3685,  1.4221, -0.5661])


In [44]:
#沿着列对x求和
sum_x_col = t.sum(x, dim = 0)
print(sum_x_col)

tensor([-1.1168,  1.2635,  0.3659, -0.0252])


In [45]:
#增加或减少维度
print(x.shape)
x_1 = x.unsqueeze(0) #在第一维前增加一个维度
print(x_1.shape)
print(x_1)

torch.Size([3, 4])
torch.Size([1, 3, 4])
tensor([[[-0.7186,  0.3988, -0.4838,  0.4351],
         [-0.5701,  0.4154,  1.4665,  0.1102],
         [ 0.1719,  0.4493, -0.6168, -0.5705]]])


In [46]:
x_2 = x.unsqueeze(1)  #在第二维度增加
print(x_2.shape)

torch.Size([3, 1, 4])


In [48]:
x_1 = x_1.squeeze(0) #减少第一维
print(x_1.shape)

torch.Size([3, 4])


In [49]:
x_2 = x_2.squeeze(1) #减少第二维
print(x_2.shape)

torch.Size([3, 4])


In [51]:
x = x.unsqueeze(0)
print(x.shape)
x = x.squeeze() #将tensor中的一维全部去掉
print(x.shape)

torch.Size([1, 3, 4])
torch.Size([3, 4])


In [59]:
x = t.randn(3, 4, 5)
print(x.shape)

#使用permute和transpose进行维度转换
x = x.permute(1, 0, 2) #permute可以重新排列tensor的维度
print(x.shape)

x = x.transpose(0, 2) #transpose可以将指定的两个维度交换
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([4, 3, 5])
torch.Size([5, 3, 4])


In [62]:
#使用view对tensor进行reshape
x = t.randn(3, 4, 5)
print(x.shape)

x = x.view(-1, 5)# -1表示任意的大小，5表示第二维的大小为5
print(x.shape)

x = x.view(5, -1)# 5 表示第一维的大小为5
print(x.shape)

x = x.view(3, 20)#重新reshape成（3， 20）的大小
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([5, 12])
torch.Size([3, 20])


另外，pytorch中的大部分操作都支持inplace操作，也就是直接对tensor进行操作而不用开辟新的内存空间，方式非常简单，一般是在操作的符号后面加上_。

In [70]:
x = t.ones(3, 3)
print(x.shape)

#unsqueeze进行inplace
x.unsqueeze_(0)
print(x.shape)

#transpose进行inplace
x.transpose_(1, 0)
print(x.shape)

#add进行inplace
x = t.ones(3, 3)
y = t.ones(3, 3)
x.add_(y)
print(x)

torch.Size([3, 3])
torch.Size([1, 3, 3])
torch.Size([3, 1, 3])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [72]:
x = t.ones(4, 4).type(t.FloatTensor)
x[1:3, 1:3] = 2
print(x)

tensor([[1., 1., 1., 1.],
        [1., 2., 2., 1.],
        [1., 2., 2., 1.],
        [1., 1., 1., 1.]])



### autograd: 自动微分

深度学习的算法本质上是通过反向传播求导数，而PyTorch的**`autograd`**模块则实现了此功能。在Tensor上的所有操作，autograd都能为它们自动提供微分，避免了手动计算导数的复杂过程。
 
~~`autograd.Variable`是Autograd中的核心类，它简单封装了Tensor，并支持几乎所有Tensor有的操作。Tensor在被封装为Variable之后，可以调用它的`.backward`实现反向传播，自动计算所有梯度~~ ~~Variable的数据结构如图2-6所示。~~



  *从0.4起, Variable 正式合并入Tensor, Variable 本来实现的自动微分功能，Tensor就能支持。读者还是可以使用Variable(tensor), 但是这个操作其实什么都没做。建议读者以后直接使用tensor*. 
  
  要想使得Tensor使用autograd功能，只需要设置`tensor.requries_grad=True`. 


~~Variable主要包含三个属性。~~
~~- `data`：保存Variable所包含的Tensor~~
~~- `grad`：保存`data`对应的梯度，`grad`也是个Variable，而不是Tensor，它和`data`的形状一样。~~
~~- `grad_fn`：指向一个`Function`对象，这个`Function`用来反向传播计算输入的梯度，具体细节会在下一章讲解。~~

在这里仅对Variable做简单介绍

In [94]:
from torch.autograd import Variable

In [95]:
x_tensor = t.randn(10, 5)
y_tensor = t.randn(10, 5)

#将tensor转换为Variable
x = Variable(x_tensor, requires_grad = True) #Variable默认不需要求梯度，如果需要则将requires_grad设置为True
y = Variable(y_tensor, requires_grad = True)
z = t.sum(x + y)
print(z.data)
print(z.grad_fn)

tensor(-8.6180)


In [96]:
#求x和y的梯度
z.backward()
print(x.grad)
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [97]:
x = Variable(t.Tensor([2]), requires_grad = True)
y = x ** 2

In [98]:
y.backward()
print(x.grad)

tensor([4.])
